/* eslint-disable @typescript-eslint/ban-types */
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

interface Station {
    number: number;
    traps: number;
    course: string;
}

interface Course {
    name: string;
    stations: Station[];
}

type useModal<T> = [
    React.FC<T>,
    Function<void>
]
