/* eslint-disable @typescript-eslint/ban-types */
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

interface Station {
    number: number;
    traps: number;
    course: string;
    trapIpAddresses: string[];
}

interface Course {
    name: string;
    stations: Station[];
}

interface Trap {
    name: string;
    ipAddress: string;
}

interface Remote {
    name: string;
    buttonDefinitions: ButtonDefinition[];
}

enum ButtonType {
    Custom = 0,
    Singles = 1,
    Doubles = 2,
}
interface ButtonDefinition {
    id: string;
    text: string;
    buttonType: ButtonType;
    position: {row: number, column: number};
    traps: trap[];
}

interface IdModalProps {
    id: string;
}

type AnyCallback = (...params: any[]) => void | Promise<void>;
